version: '3.8'

services:
  app:
    container_name: node_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    depends_on:
      - mongo
    environment:
      MONGO_URI : "mongodb://mongo:27017/mydatabase"


  mongo:
    container_name: mongo_db
    image: mongo:latest
    ports:
      - '27017:27017'

